### ISSUE TITLE
想问一下为什么 `controller` 下扫描不支持多层级呢？

### ISSUE THREAD

**Issue by myadream** [archine/gin-plus#1]
我看 [mvc2](https://github.com/archine/gin-plus/blob/v2/ast/mvc2/main.go) 中只扫描当前层级模块。
另外想问一下 https://github.com/archine/ioc 这个仓库是什么开源协议, 我这边有一个开源项目有使用到这个项目...

**Comment by archine** [comment]
MIT协议，





------------------ 原始邮件 ------------------
发件人: myadream ***@***.***&gt;
发送时间: 2023年10月13日 18:21
收件人: archine/gin-plus ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [archine/gin-plus] 想问一下为什么 `controller` 下扫描不支持多层级呢？ (Issue #1)





 
我看 mvc2 中只扫描当前层级模块。
 另外想问一下 https://github.com/archine/ioc 这个仓库是什么开源协议, 我这边有一个开源项目有使用到这个项目...

**Comment by archine** [comment]
额，目前不支持递归目录向下扫描，但是可以通过执行多次来代替





------------------ 原始邮件 ------------------
发件人: myadream ***@***.***&gt;
发送时间: 2023年10月13日 18:21
收件人: archine/gin-plus ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [archine/gin-plus] 想问一下为什么 `controller` 下扫描不支持多层级呢？ (Issue #1)





 
我看 mvc2 中只扫描当前层级模块。
 另外想问一下 https://github.com/archine/ioc 这个仓库是什么开源协议, 我这边有一个开源项目有使用到这个项目...

**Comment by myadream** [comment]
好吧， 多次执行的话需要在顶层模块手动引入对应的包所以比较麻烦, 我尝试调整一下吧。感谢回复
