### ISSUE TITLE
关于 controller 多层级目录扫描

### ISSUE THREAD

**Issue by myadream** [archine/gin-plus#2]
基于 `mvc2` 进行调整为多层级目录扫描实现方式，如果有考虑调整希望对你有帮助

扫描：
https://github.com/QiYangApp/service-api/blob/main/src/script/ioc/main.go

注入：
https://github.com/QiYangApp/service-api/blob/main/src/core/inject/inject.go

**Comment by myadream** [comment]
同改进可以自动进行绑定请求参数

https://github.com/QiYangApp/service-api/blob/main/src/core/inject/inject.go#L81

**Comment by archine** [comment]
v3版本已支持多级扫描及过滤
